#!/bin/bash
brew update
brew upgrade
brew prune
brew cleanup

for c in $(brew cask list -1); do
    info=$(brew cask info $c)
    current_ver=$(echo "$info" | gcut -d$'\n' -f1 | gtr -d ' ' | gcut -d':' -f 2 | awk -F \( '{ print $1 }')
    installed_ver=$(echo "$info" | gcut -d$'\n' -f3 | gcut -d' ' -f 1 | rev | gcut -d'/' -f 1 | rev | gcut -d':' -f 1)
    if [ "$installed_ver" != "$current_ver" ]; then
        read -p  "$c installed version is '$installed_ver', but the current version is '$current_ver', do you want to upgrade $c ? [y/n] " answer
	if [ $answer = y ] ; then
        brew cask upgrade --force $c
    fi
fi
done
brew cask cleanup
brew doctor
